apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quantum-shield.fullname" . }}
  labels:
    {{- include "quantum-shield.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ printf "postgresql+asyncpg://%s:%s@%s:5432/%s" .Values.postgresql.user .Values.postgresql.password (include "quantum-shield.postgresql.fullname" .) .Values.postgresql.database | b64enc | quote }}
  audit-key-v1: {{ .Values.secrets.auditKeys.v1 | b64enc | quote }}
  api-key-operator: {{ .Values.secrets.apiKeys.operator | b64enc | quote }}
  api-key-auditor: {{ .Values.secrets.apiKeys.auditor | b64enc | quote }}
  {{- if eq .Values.env.KMS_PROVIDER "vault" }}
  vault-token: {{ .Values.secrets.vaultToken | default "" | b64enc | quote }}
  {{- end }}